# Sinatra::SwaggerExposer

Create Swagger endpoint for your Sinatra application.

This Sinatra extension enable you to add metadata to your code and to expose your API as a Swagger endpoint.

It currently doesn't use all the Swagger options, so if you need one that is missing please contribute or open an issue.

## Design choices

- All the declarations are validated when the server is started
- The declarations are defined to look as ruby-ish as possible

WARNING: Currently a work in progress prototype, use at your own risks.

To use it in your app :

[source,ruby]
----
require 'sinatra/swagger-exposer/swagger-exposer'

class MyApp < Sinatra::Base

  register Sinatra::SwaggerExposer

  swagger_info(
      {
          version: '0.0.1',
          title: 'May app',
          description: 'My wonderful app',
          license: {
              name: 'MIT',
              url: 'http://opensource.org/licenses/MIT'
          }
      }
  )

  type 'Status',
               {
                   :properties => {
                       :status => {
                           :type => String,
                           :example => 'OK,
                       },
                   },
                   :required => [:status]
               }

  endpoint_description 'Base method to ping'
  endpoint_response 200, 'Standard response', 'Status'
  endpoint_tags 'Ping'
  get '/' do
    json({'status' => 'OK'})
  end

end
----

The swagger json endpoint will be exposed at `/swagger_doc.json`.

## Detailed example

A more complete example is available link:https://github.com/archiloque/sinatra-swagger-exposer/tree/master/example[here].

## Resources

link:https://raw.githubusercontent.com/swagger-api/swagger-spec/master/schemas/v2.0/schema.json[The swagger json schema].

link:https://github.com/swagger-api/swagger-spec/tree/master/examples/v2.0/json[Swagger json examples].

## License

This software is released under the MIT license.
