# Sinatra::SwaggerExposer

image:https://codeclimate.com/github/archiloque/sinatra-swagger-exposer/badges/gpa.svg["Code status", link=https://codeclimate.com/github/archiloque/sinatra-swagger-exposer]
image:https://travis-ci.org/archiloque/sinatra-swagger-exposer.svg?branch=master["Build Status", link="https://travis-ci.org/archiloque/sinatra-swagger-exposer"]
image:https://coveralls.io/repos/archiloque/sinatra-swagger-exposer/badge.svg?branch=master["Coverage Status", link="https://coveralls.io/r/archiloque/sinatra-swagger-exposer?branch=master"]

Create Swagger endpoint for your Sinatra application.

This Sinatra extension enable you to add metadata to your code and to expose your API as a Swagger endpoint.

I'm adding features as I need them and it currently doesn't use all the Swagger options, so if you need one that is missing please open an issue or contribute.

## Design choices

- All the declarations are validated when the server is started
- The declarations are defined to look as ruby-ish as possible

WARNING: Currently a work in progress prototype, use at your own risks.

To use it in your app :

[source,ruby]
----
require 'sinatra/swagger-exposer/swagger-exposer'

class MyApp < Sinatra::Base

  register Sinatra::SwaggerExposer

  general_info(
      {
          version: '0.0.1',
          title: 'May app',
          description: 'My wonderful app',
          license: {
              name: 'MIT',
              url: 'http://opensource.org/licenses/MIT'
          }
      }
  )

  type 'Status',
               {
                   :properties => {
                       :status => {
                           :type => String,
                           :example => 'OK,
                       },
                   },
                   :required => [:status]
               }

  endpoint_description 'Base method to ping'
  endpoint_response 200, 'Standard response', 'Status'
  endpoint_tags 'Ping'
  get '/' do
    json({'status' => 'OK'})
  end

end
----

The swagger json endpoint will be exposed at `/swagger_doc.json`.

## Detailed example

A more complete example is available link:https://github.com/archiloque/sinatra-swagger-exposer/tree/master/example[here].

## Resources

- link:https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md[Swagger RESTful API Documentation Specification].
- link:https://github.com/swagger-api/swagger-spec/tree/master/examples/v2.0/json[Swagger json examples].
- link:https://raw.githubusercontent.com/swagger-api/swagger-spec/master/schemas/v2.0/schema.json[The swagger json schema].

## License

This software is released under the MIT license.
